export const labels = {
	en: {
		lib: "Library",
		downloadApp: "Download app",
		shortcuts: "Keyboard shortcuts",
		sort: "Sort",
		settings: "Settings",
		addBook: "Add book",
		play: "Play",
		pause: "Pause",
		bookOpts: "Book options",
		bookInfo: "Book info",
		fileList: "File list",
		bookmarks: "Bookmarks",
		delBook: "Delete book",
		noBooks: "No books",
		back: "Back",
		prevTrack: "Previous track",
		rewBack: "Rewind backward",
		revFwd: "Rewind forward",
		nextTrack: "Next track",
		sleepTimer: "Sleep timer",
		addBookmark: "Add bookmark",
		delBookmark: "Delete bookmark",
		jumpTo: "Jump to",
		jumpToTime: "Jump to time",
		eq: "Equalizer",
		eqOff: "EQ off",
		eqLB: "Less Bass",
		eqNB: "No Bass",
		playSpeed: "Playback speed",
		volume: "Volume",
		more: "More",
		info: "Info",
		author: "Author",
		book: "Book",
		year: "Year",
		narrator: "Narrator",
		genre: "Genre",
		label: "Label",
		lang: "Language",
		timing: "Timing",
		totalTime: "Total time",
		added: "Added",
		lastPlay: "Last played",
		finished: "Finished",
		quality: "Quality",
		codec: "Codec",
		bitrate: "Bitrate",
		sr: "Sample rate",
		storage: "Storage",
		appMem: "App memory",
		appMem2: "App memory",
		devStor: "Device storage",
		files: "Files",
		del: "Delete",
		title: "Title",
		time: "Time",
		save: "Save",
		showBookmarks: "Show bookmarks",
		general: "General",
		keySP: "Play / Pause",
		keyArrH: "Rewind backward / forward",
		keyArrV: "Volume down / up",
		keyEsc: "Close modal",
		keySlE: "Set time",
		keySlArr: "Start / stop timer",
		auto: "Auto",
		dark: "Dark",
		light: "Light",
		track: "Track",
		rewind: "Rewind",
		remaining: "Remaining",
		devFiles: "Device files",
		colorScheme: "Color scheme",
		rewindTime: "Rewind time",
		mediaKeys: "Prev/next media keys",
		timeDisplay: "Time display",
		appColor: "App color",
		booksStorage: "New books storage",
		booksStorageN1: "Book files will be read from the device's storage. The app will have a smaller size but may ask for permissions more often.",
		booksStorageN2: "New books will be stored in apps memory. This option may cause higher app size, but app will not ask for permissions.",
		appStorageUsed: "App storage usage",
		noBookmarks: "You have no bookmarks for this book.",
		start: "Start",
		start2: "Start",
		hour: "Hour",
		minute: "Minute",
		second: "Second",
		cancel: "Cancel",
		timerNote1: "Stop playback in",
		timerNote2: "Playback will stop in",
		newest: "Newest",
		recentlyPlayed: "Recently played",
		duration: "Duration",
		titleAz: "Title A-Z",
		iosInst1: '1. Press the "Share" button',
		iosInst2: '2. Select "Add to Home Screen" from the popup',
		iosInst3: '3. Tap "Add" in the top right corner',
		permRequired: "Permission is required to play this audiobook",
		clFile: "Unable to load file",
		bmSaved: "Bookmark saved",
		bmRemoved: "Bookmark removed",
		editFileList: "Edit file list",
		fileNameSource: "Items name source",
		fileName: "File name",
		listUpdated: "File list was updated"
	},
	sk: {
		lib: "Knižnica",
		downloadApp: "Stiahnuť aplikáciu",
		shortcuts: "Klávesové skratky",
		sort: "Zoradiť",
		settings: "Nastavenia",
		addBook: "Pridať knihu",
		play: "Prehrať",
		pause: "Pozastaviť",
		bookOpts: "Možnosti knihy",
		bookInfo: "Informácie o knihe",
		fileList: "Zoznam súborov",
		bookmarks: "Záložky",
		delBook: "Odstrániť knihu",
		noBooks: "Žiadne knihy",
		back: "Späť",
		prevTrack: "Predchádzajúca stopa",
		rewBack: "Preskočiť dozadu",
		revFwd: "Preskočiť dopredu",
		nextTrack: "Nasledujúca stopa",
		sleepTimer: "Časovač spánku",
		addBookmark: "Pridať záložku",
		delBookmark: "Odstrániť záložku",
		jumpTo: "Preskočiť na",
		jumpToTime: "Preskočiť na čas",
		eq: "Ekvalizér",
		eqOff: "EQ vypnutý",
		eqLB: "Menej basov",
		eqNB: "Bez basov",
		playSpeed: "Rýchlosť prehrávania",
		volume: "Hlasitosť",
		more: "Viac",
		info: "Informácie",
		author: "Autor",
		book: "Kniha",
		year: "Rok",
		narrator: "Rozprávač",
		genre: "Žáner",
		label: "Vydaveteľstvo",
		lang: "Jazyk",
		timing: "Časovanie",
		totalTime: "Celkový čas",
		added: "Pridané",
		lastPlay: "Naposledy prehrávané",
		finished: "Dokončené",
		quality: "Kvalita",
		codec: "Kodek",
		bitrate: "Bitová rýchlosť",
		sr: "Vzorkovacia frekvencia",
		storage: "Úložisko",
		appMem: "Aplikácia",
		appMem2: "Pamäť aplikácie",
		devStor: "Úložisko zariadenia",
		files: "Súbory",
		del: "Odstrániť",
		title: "Názov",
		time: "Čas",
		save: "Uložiť",
		showBookmarks: "Zobraziť záložky",
		general: "Všeobecné",
		keySP: "Prehrať / Pozastaviť",
		keyArrH: "Preskočiť dozadu / dopredu",
		keyArrV: "Znížiť / Zvýšiť hlasitosť",
		keyEsc: "Zavrieť vyskakovacie okno",
		keySlE: "Nastaviť čas",
		keySlArr: "Spustiť / zastaviť časovač",
		auto: "Auto",
		dark: "Tmavá",
		light: "Svetlá",
		track: "Stopa",
		rewind: "Pretáčanie",
		remaining: "Zostáva",
		devFiles: "Súbory",
		colorScheme: "Farebná schéma",
		rewindTime: "Čas pretáčania",
		mediaKeys: "Mediálne klávesy («/»)",
		timeDisplay: "Zobrazenie času",
		appColor: "Farba aplikácie",
		booksStorage: "Úložisko nových kníh",
		booksStorageN1: "Súbory kníh budú čítané z úložiska zariadenia. Aplikácia bude mať menšiu veľkosť, ale môže častejšie žiadať o povolenia.",
		booksStorageN2: "Nové knihy budú uložené v pamäti aplikácie. Táto možnosť môže zvýšiť veľkosť aplikácie, ale nebude vyžadovať povolenia.",
		appStorageUsed: "Využitie úložiska aplikácie",
		noBookmarks: "Pre túto knihu nemáte žiadne záložky.",
		start2: "Spustiť",
		start: "Začiatok",
		hour: "Hodina",
		minute: "Minúta",
		second: "Sekunda",
		cancel: "Zrušiť",
		timerNote1: "Zastaviť prehrávanie za",
		timerNote2: "Prehrávanie sa zastaví za",
		newest: "Najnovšie",
		recentlyPlayed: "Naposledy prehrávané",
		duration: "Trvanie",
		titleAz: "Názov A-Z",
		iosInst1: '1. Stlačte tlačidlo "Zdieľať"',
		iosInst2: '2. Vyberte "Pridať na plochu" z ponuky',
		iosInst3: '3. Klepnite na "Pridať" v pravom hornom rohu',
		permRequired: "Na prehrávanie tejto audioknihy sa vyžaduje povolenie",
		clFile: "Nie je možné načítať súbor",
		bmSaved: "Záložka bola uložená",
		bmRemoved: "Záložka bola odstránená",
		editFileList: "Upraviť zoznam súborov",
		fileNameSource: "Zdroj názvov položiek",
		fileName: "Názov súboru",
		listUpdated: "Zoznam súborov bol aktualizovaný"
	},
	cz: {
		lib: "Knihovna",
		downloadApp: "Stáhnout aplikaci",
		shortcuts: "Klávesové zkratky",
		sort: "Seřadit",
		settings: "Nastavení",
		addBook: "Přidat knihu",
		play: "Přehrát",
		pause: "Pozastavit",
		bookOpts: "Možnosti knihy",
		bookInfo: "Informace o knize",
		fileList: "Seznam souborů",
		bookmarks: "Záložky",
		delBook: "Odstranit knihu",
		noBooks: "Žádné knihy",
		back: "Zpět",
		prevTrack: "Předchozí stopa",
		rewBack: "Přetočit zpět",
		revFwd: "Přetočit vpřed",
		nextTrack: "Další stopa",
		sleepTimer: "Časovač spánku",
		addBookmark: "Přidat záložku",
		delBookmark: "Odstranit záložku",
		jumpTo: "Přeskočit na",
		jumpToTime: "Přeskočit na čas",
		eq: "Ekvalizér",
		eqOff: "EQ vypnutý",
		eqLB: "Méně basů",
		eqNB: "Bez basů",
		playSpeed: "Rychlost přehrávání",
		volume: "Hlasitost",
		more: "Více",
		info: "Informace",
		author: "Autor",
		book: "Kniha",
		year: "Rok",
		narrator: "Vypravěč",
		genre: "Žánr",
		label: "Vydavatelství",
		lang: "Jazyk",
		timing: "Časování",
		totalTime: "Celkový čas",
		added: "Přidáno",
		lastPlay: "Naposledy přehráno",
		finished: "Dokončeno",
		quality: "Kvalita",
		codec: "Kodek",
		bitrate: "Bitrate",
		sr: "Vzorkovací frekvence",
		storage: "Úložiště",
		appMem: "Aplikace",
		appMem2: "Paměť aplikace",
		devStor: "Úložiště zařízení",
		files: "Soubory",
		del: "Smazat",
		title: "Název",
		time: "Čas",
		save: "Uložit",
		showBookmarks: "Zobrazit záložky",
		general: "Obecné",
		keySP: "Přehrát / Pozastavit",
		keyArrH: "Přetočit zpět / vpřed",
		keyArrV: "Zeslabit / Zesílit hlasitost",
		keyEsc: "Zavřít vyskakovací okno",
		keySlE: "Nastavit čas",
		keySlArr: "Spustit / zastavit časovač",
		auto: "Auto",
		dark: "Tmavá",
		light: "Světlá",
		track: "Stopa",
		rewind: "Přetáčení",
		remaining: "Zbývá",
		devFiles: "Soubory",
		colorScheme: "Barevné schéma",
		rewindTime: "Čas přetáčení",
		mediaKeys: "Mediální klávesy («/»)",
		timeDisplay: "Zobrazení času",
		appColor: "Barva aplikace",
		booksStorage: "Úložiště nových knih",
		booksStorageN1: "Soubory knih budou čteny z úložiště zařízení. Aplikace bude menší, ale může častěji žádat o oprávnění.",
		booksStorageN2: "Nové knihy budou ukládány do paměti aplikace. Tato možnost může zvětšit velikost aplikace, ale nebude vyžadovat oprávnění.",
		appStorageUsed: "Využití úložiště aplikace",
		noBookmarks: "Pro tuto knihu nemáte žádné záložky.",
		start2: "Spustit",
		start: "Začátek",
		hour: "Hodina",
		minute: "Minuta",
		second: "Sekunda",
		cancel: "Zrušit",
		timerNote1: "Zastavit přehrávání za",
		timerNote2: "Přehrávání se zastaví za",
		newest: "Nejnovější",
		recentlyPlayed: "Naposledy přehráno",
		duration: "Doba trvání",
		titleAz: "Název A-Z",
		iosInst1: '1. Stiskněte tlačítko "Sdílet"',
		iosInst2: '2. Vyberte "Přidat na plochu" z nabídky',
		iosInst3: '3. Klepněte na "Přidat" v pravém horním rohu',
		permRequired: "K přehrávání této audioknihy je vyžadováno povolení",
		clFile: "Nelze načíst soubor",
		bmSaved: "Záložka byla uložena",
		bmRemoved: "Záložka byla odstraněna",
		editFileList: "Upravit seznam souborů",
		fileNameSource: "Zdroj názvů položek",
		fileName: "Název souboru",
		listUpdated: "Seznam souborů byl aktualizován"
	}
}